/*
    날짜:2025/07/18
    이름:장진원
    내용:SQL 연습문제1
*/

--실습1-1
alter session set "_ORACLE_SCRIPT"=true;
create user shop identified by 1234;
grant connect,resource,unlimited tablespace to shop;

--실습 1-2

drop table customer;

create table Customer(
    CID varchar2(20) primary key,
    name varchar2(20) not null,
    hp char(13) unique,
    address varchar2(200),
    rdate date not null
);

create table Product(
    pno number(20) primary key,
    pname varchar2(30) not null,
    stock number default 0 not null ,
    price number default null,
    company char(20) not null
);

create table Orders(
    ORD_NO number GENERATED BY DEFAULT AS IDENTITY primary key,
    ORD_CID varchar2(20) not null,
    ORD_PNO number not null,
    ORD_CNT number default 1 not null ,
    ORD_DATE date not null
);


--실습 1-3
insert into customer values('c101','김유신','010-1234-1001','김해시 봉황동','2022-01-01');
insert into customer values('c102','김춘추','010-1234-1002','경주시 보운동','2022-01-02');
insert into customer values('c103','장보고','010-1234-1003','완도군 청산면','2022-01-03');
insert into customer values('c104','강감찬','010-1234-1004','서울시 마포구','2022-01-04');
insert into customer values('c105','이성계',null,null,'2022-01-05');
insert into customer values('c106','정철','010-1234-1006','경기도 용인시','2022-01-06');
insert into customer values('c107','허준',null,null,'2022-01-07');
insert into customer values('c108','이순신','010-1234-1008','서울시 영등포구','2022-01-08');
insert into customer values('c109','송상현','010-1234-1009','부산시 동래구','2022-01-09');
insert into customer values('c110','정약용','010-1234-1010','경기도 광주시','2022-01-10');
insert into customer values('c111','aaa','','','2022-01-11');
delete from customer;

insert into product values(1,'새우깡',5000,1500,'농심');
insert into product values(2,'초코파이',2500,2500,'오리온');
insert into product values(3,'포카칩',3600,1700,'오리온');
insert into product values(4,'양파링',1250,1800,'농심');
insert into product values(5,'죠리퐁',2200,null,'크라운');
insert into product values(6,'마가렛트',3500,3500,'롯데');
insert into product values(7,'뿌셔뿌셔',1650,1200,'오뚜기');

//insert into orders(ord_cid,ord_pno,ord_cnt,ord_date) values('c102',3,2,TO_DATE('2022-07-01 13:15:10', 'YYYY-MM-DD HH24:MI:SS'));
insert into orders(ord_cid,ord_pno,ord_cnt,ord_date) values('c102',3,2,'2022-07-01 13:15:10');
insert into orders(ord_cid,ord_pno,ord_cnt,ord_date) values('c101',4,1,'2022-07-01 14:16:11');
insert into orders(ord_cid,ord_pno,ord_cnt,ord_date) values('c108',1,1,'2022-07-01 17:23:18');
insert into orders(ord_cid,ord_pno,ord_cnt,ord_date) values('c109',6,5,'2022-07-02 10:46:36');
insert into orders(ord_cid,ord_pno,ord_cnt,ord_date) values('c102',2,1,'2022-07-03 09:15:37');
insert into orders(ord_cid,ord_pno,ord_cnt,ord_date) values('c101',7,3,'2022-07-03 12:35:12');
insert into orders(ord_cid,ord_pno,ord_cnt,ord_date) values('c110',1,2,'2022-07-03 16:55:36');
insert into orders(ord_cid,ord_pno,ord_cnt,ord_date) values('c104',2,4,'2022-07-04 14:23:23');
insert into orders(ord_cid,ord_pno,ord_cnt,ord_date) values('c102',1,3,'2022-07-04 21:54:34');
insert into orders(ord_cid,ord_pno,ord_cnt,ord_date) values('c107',6,1,'2022-07-05 14:21:03');

drop table orders;
delete from orders;


--실습 1-4
select * from customer;
--실습 1-5
select cid,name,hp from customer;
--실습 1-6
select * from product;
--실습 1-7
select company from product;
--실습 1-8
select distinct company from product;
--실습 1-9
select pname,price from product;
--실습 1-10
select pname,price+500 as "조정단가" from product;
--실습 1-11
select pname,stock,price from product where company='오리온';
--실습 1-12
select ord_pno,ord_cnt,ord_date from orders where ord_cid='c102';
--실습 1-13
select ord_pno,ord_cnt,ord_date from orders where ord_cid='c102' and ord_cnt>=2;
--실습 1-14
select * from product where price>=1000 and 2000>price;
--실습 1-15
select cid,name,hp,address from customer where name like '김%';
--실습 1-16
select cid,name,hp,address from customer where name like '__';
--실습 1-17
SELECT * FROM Customer WHERE hp is null;
--실습 1-18
SELECT * FROM Customer WHERE address is not null;
--실습 1-19
SELECT * FROM Customer order by rdate desc;
--실습 1-20
SELECT * FROM Orders WHERE ord_cnt>=3 order by ord_cnt desc,ord_no asc;
--실습 1-21
select avg(price) from product;
--실습 1-22
select sum(stock) as "재고량 합계" from product where company = '농심';
--실습 1-23
select count(*) as 고객수 from customer;
--실습 1-24
select count(distinct company) as "제조업체 수" from product;
--실습 1-25
SELECT ORD_PNO as "주문 상품번호", SUM(ORD_CNT) as "총 주문수량" FROM Orders group by ord_pno order by ord_pno;
--실습 1-26
SELECT company AS 제조업체, COUNT(*) AS 제품수, MAX(price) AS 최고가 FROM Product group by company order by company;
--실습 1-27
 SELECT company AS 제조업체, COUNT(*) AS 제품수, MAX(price) AS 최고가 FROM
 Product GROUP BY company having count(company)>=2;
--실습 1-28
 SELECT ORD_PNO, ORD_CID, SUM(ORD_CNT) AS "총 주문수량" FROM Orders group by ord_pno,ord_cid order by ord_pno;
--실습 1-29
SELECT ORD_CID, PNAME from Orders a JOIN Product b ON a.ORD_PNO = b.PNO where a.ord_cid='c102';
--실습 1-30
SELECT ORD_CID, name, pname, ORD_DATE from Orders a
 JOIN Customer b on a.ORD_CID = b.cid
 JOIN Product c on a.ORD_PNO = c.pno
 where TO_CHAR(a.ORD_DATE, 'MM-DD') = '07-03';
 
 
SELECT ORD_CID, name, pname, ORD_DATE from Orders a
 JOIN Customer b on a.ORD_CID = b.cid
 JOIN Product c on a.ORD_PNO = c.pno
 where ord_date like '2022-07-03%';
 
 SELECT ORD_CID, name, pname, ORD_DATE from Orders a
 JOIN Customer b on a.ORD_CID = b.cid
 JOIN Product c on a.ORD_PNO = c.pno
 where substr(ord_date,1,10)='2022-07-03';
 